const { useState, useEffect, useRef, useCallback } = React;
const { motion, AnimatePresence } = window.Motion;
const { Button } = window;

// Обновленная база с объемными и осмысленными абзацами
const textsData = {
    en: [
        "The universe is an unimaginably vast place, constantly expanding at an accelerating rate. Scientists believe that galaxies are moving further apart every second, driven by a mysterious force known as dark energy. Even with our most advanced telescopes, we have only mapped a tiny fraction of the observable cosmos.",
        "Octopuses are incredibly fascinating marine creatures with a highly developed nervous system. They possess three hearts, blue blood, and have the astonishing ability to change both their color and texture to blend seamlessly with their surroundings. Their intelligence allows them to solve complex puzzles and even escape from seemingly secure enclosures.",
        "Deep beneath the surface of our planet lies a core so incredibly hot that it matches the temperature of the surface of the sun. The Earth's magnetic field, which protects us from harmful solar radiation, is generated by the movement of molten iron and nickel in the outer core.",
        "Artificial intelligence has rapidly evolved from simple rule-based algorithms to complex neural networks capable of learning. Today, machine learning models can recognize images, translate languages in real time, and even generate creative artwork, fundamentally changing the way we interact with modern technology.",
        "The Great Barrier Reef is the largest living structure on Earth and can even be seen from outer space. It is composed of billions of tiny organisms known as coral polyps, creating a complex and incredibly diverse ecosystem that supports thousands of different marine species.",
        "Water is the only common substance that occurs naturally in all three common states of matter: solid, liquid, and gas. What makes it even more unusual is that its solid form, ice, is less dense than its liquid form, which is why icebergs float on the surface of the ocean.",
        "The history of space exploration changed forever when humans first set foot on the lunar surface. The Apollo missions not only demonstrated incredible technological achievements but also brought back invaluable samples of moon rocks that have helped scientists understand the formation of our solar system.",
        "Forests play a critical role in mitigating climate change by absorbing large amounts of carbon dioxide from the atmosphere. Additionally, they provide habitats for countless species of flora and fauna, making their preservation essential for maintaining global biodiversity and ecological balance.",
        "The concept of time has fascinated philosophers and physicists for centuries. According to the theory of relativity, time is not absolute but is interwoven with space into a single continuum, meaning that it can slow down or speed up depending on how fast you are moving.",
        "Volcanoes are both destructive and creative forces of nature. While their eruptions can devastate surrounding landscapes with lava and ash, over millions of years, they also create new landmasses and enrich the soil with vital minerals, allowing new life to eventually thrive."
    ],
    ru: [
        "Космос представляет собой невероятно огромное и таинственное пространство, которое постоянно расширяется с ускорением. Ученые предполагают, что галактики отдаляются друг от друга каждую секунду под воздействием загадочной темной энергии. Даже с помощью самых мощных телескопов мы смогли изучить лишь ничтожно малую часть наблюдаемой Вселенной.",
        "Осьминоги — это удивительные морские обитатели с высокоразвитой нервной системой и невероятным уровнем интеллекта. Они обладают тремя сердцами, голубой кровью и уникальной способностью мгновенно менять цвет и текстуру своей кожи. Их интеллект позволяет им решать сложные головоломки и даже сбегать из закрытых аквариумов.",
        "Глубоко под поверхностью нашей планеты находится ядро, температура которого сравнима с температурой поверхности Солнца. Магнитное поле Земли, которое надежно защищает нас от губительной космической радиации, генерируется непрерывным движением расплавленного железа и никеля во внешнем ядре.",
        "Искусственный интеллект прошел долгий путь развития от простых алгоритмов до сложнейших нейронных сетей, способных к глубокому обучению. Сегодня современные модели могут распознавать изображения, переводить тексты в реальном времени и даже создавать произведения искусства, меняя наш привычный мир.",
        "Тропические леса Амазонки часто называют легкими нашей планеты, так как они производят огромное количество земного кислорода. Эта уникальная экосистема является домом для миллионов видов растений, насекомых и животных, многие из которых до сих пор остаются совершенно неизвестными современной науке.",
        "Вода является единственным веществом на Земле, которое естественно встречается в трех агрегатных состояниях: твердом, жидком и газообразном. Еще более удивительным фактом является то, что лед обладает меньшей плотностью, чем жидкая вода, благодаря чему айсберги могут спокойно плавать на поверхности океана.",
        "История освоения космоса навсегда изменилась в тот момент, когда человек впервые ступил на поверхность Луны. Миссии программы Аполлон не только продемонстрировали невероятные технологические достижения, но и доставили на Землю бесценные образцы лунного грунта для дальнейших масштабных исследований.",
        "Вулканы представляют собой одновременно разрушительную и созидательную силу природы. Хотя их извержения могут уничтожать целые ландшафты потоками раскаленной лавы, со временем они формируют новые участки суши и обогащают почву полезными минералами, позволяя зарождаться новой жизни.",
        "Время веками оставалось главной загадкой для величайших философов и физиков. Согласно теории относительности, время не абсолютно, а тесно связано с пространством в единый континуум, что означает его способность замедляться или ускоряться в зависимости от скорости вашего движения.",
        "Большой Барьерный риф является крупнейшим живым организмом на планете, который можно увидеть даже из открытого космоса. Он состоит из миллиардов крошечных коралловых полипов, образующих невероятно сложную экосистему, поддерживающую существование тысяч различных видов морских обитателей."
    ]
};

const layouts = {
    en: [
        ["q","w","e","r","t","y","u","i","o","p", "[", "]"],
        ["a","s","d","f","g","h","j","k","l", ";", "'"],
        ["z","x","c","v","b","n","m", ",", ".", "/"],
        [" "]
    ],
    ru: [
        ["й","ц","у","к","е","н","г","ш","щ","з","х","ъ"],
        ["ф","ы","в","а","п","р","о","л","д","ж","э"],
        ["я","ч","с","м","и","т","ь","б","ю", "."],
        [" "]
    ]
};

const TypingTest = ({ onBack }) => {
    const [lang, setLang] = useState('en');
    const [text, setText] = useState("");
    const [currentIndex, setCurrentIndex] = useState(0);
    const [errors, setErrors] = useState(0);
    const [combo, setCombo] = useState(0);
    const [maxCombo, setMaxCombo] = useState(0);
    const [startTime, setStartTime] = useState(null);
    const [endTime, setEndTime] = useState(null);
    const [pressedKey, setPressedKey] = useState(null);
    const [isErrorKey, setIsErrorKey] = useState(false);
    const [shake, setShake] = useState(false);

    const textContainerRef = useRef(null);

    const generateText = useCallback((currentLang) => {
        const list = textsData[currentLang];
        let selectedFacts = [];
        // Выбираем 1 или 2 больших абзаца для оптимальной длины теста
        const factCount = Math.floor(Math.random() * 2) + 1; 
        
        while(selectedFacts.length < factCount) {
            let randomFact = list[Math.floor(Math.random() * list.length)];
            // Защита от дублирования одного и того же абзаца
            if (!selectedFacts.includes(randomFact)) {
                selectedFacts.push(randomFact);
            }
        }
        
        return selectedFacts.join(" ") + " ";
    }, []);

    useEffect(() => {
        resetGame(lang);
    }, [lang, generateText]);

    const resetGame = (currentLang = lang) => {
        setText(generateText(currentLang));
        setCurrentIndex(0);
        setErrors(0);
        setCombo(0);
        setMaxCombo(0);
        setStartTime(null);
        setEndTime(null);
        setPressedKey(null);
    };

    useEffect(() => {
        if (textContainerRef.current) {
            const currentElement = textContainerRef.current.querySelector('.current');
            if (currentElement) {
                currentElement.scrollIntoView({ behavior: 'smooth', block: 'center' });
            }
        }
    }, [currentIndex]);

    useEffect(() => {
        const handleKeyDown = (e) => {
            if (e.key === "Shift" || e.key === "Control" || e.key === "Alt" || e.key === "Meta" || e.key === "Backspace" || e.key === "CapsLock") return;
            if (e.key === " ") e.preventDefault();
            if (currentIndex >= text.length) return;

            const actualKey = e.key; 
            const visualKey = e.key.toLowerCase(); 
            
            setPressedKey(visualKey);
            
            if (!startTime) setStartTime(Date.now());

            const expectedChar = text[currentIndex];

            if (actualKey === expectedChar) {
                setIsErrorKey(false);
                const newCombo = combo + 1;
                setCombo(newCombo);
                if (newCombo > maxCombo) setMaxCombo(newCombo);
                
                const nextIndex = currentIndex + 1;
                setCurrentIndex(nextIndex);
                if (nextIndex === text.length) setEndTime(Date.now());
            } else {
                setIsErrorKey(true);
                setErrors(prev => prev + 1);
                setCombo(0); 
                setShake(true);
                setTimeout(() => setShake(false), 300);
            }
            
            setTimeout(() => { setPressedKey(null); setIsErrorKey(false); }, 150);
        };

        window.addEventListener("keydown", handleKeyDown);
        return () => window.removeEventListener("keydown", handleKeyDown);
    }, [currentIndex, text, startTime, combo, maxCombo]);

    const calculateStats = () => {
        if (currentIndex === 0) return { wpm: 0, accuracy: 100 };
        const timeElapsed = endTime ? (endTime - startTime) / 1000 / 60 : (Date.now() - startTime) / 1000 / 60;
        const wordsTyped = currentIndex / 5;
        const wpm = timeElapsed > 0 ? Math.round(wordsTyped / timeElapsed) : 0;
        const totalAttempts = currentIndex + errors;
        const accuracy = totalAttempts > 0 ? Math.round((currentIndex / totalAttempts) * 100) : 100;
        return { wpm, accuracy };
    };

    const stats = calculateStats();
    const expectedKey = text[currentIndex]?.toLowerCase(); 
    const currentLayout = layouts[lang];
    const progress = (currentIndex / text.length) * 100;

    return (
        <motion.div 
            className="glass-panel"
            initial={{ opacity: 0, y: 30 }}
            animate={shake ? { x: [-10, 10, -10, 10, 0], opacity: 1, y: 0 } : { opacity: 1, y: 0 }}
            transition={shake ? { duration: 0.3 } : { duration: 0.6, ease: "easeOut" }}
            style={{ width: '100%', display: 'flex', flexDirection: 'column', gap: '25px', padding: '30px' }}
        >
            <header className="type-header">
                <div className="title-group">
                    <div className="type-title">Pro<span>Type</span></div>
                    <div className="lang-switch">
                        <button className={`lang-btn ${lang === 'en' ? 'active' : ''}`} onClick={() => setLang('en')}>English</button>
                        <button className={`lang-btn ${lang === 'ru' ? 'active' : ''}`} onClick={() => setLang('ru')}>Русский</button>
                    </div>
                </div>
                
                <div className="stats-grid">
                    <div className="stat-box">
                        <span className="stat-label">Комбо</span>
                        <span className={`stat-value ${combo > 10 ? 'combo-glow' : ''}`}>x{combo}</span>
                    </div>
                    <div className="stat-box">
                        <span className="stat-label">Точность</span>
                        <span className="stat-value" style={{color: stats.accuracy < 90 ? "#f43f5e" : "#10b981"}}>{stats.accuracy}%</span>
                    </div>
                    <div className="stat-box">
                        <span className="stat-label">Скорость</span>
                        <span className="stat-value" style={{color: "#0ea5e9"}}>{stats.wpm} WPM</span>
                    </div>
                </div>
            </header>

            <div className="text-container">
                <div className="text-display" ref={textContainerRef}>
                    {text.split('').map((char, index) => {
                        let statusClass = "";
                        if (index < currentIndex) statusClass = "correct";
                        else if (index === currentIndex) statusClass = "current";
                        
                        return <span key={index} className={`char ${statusClass}`}>{char}</span>;
                    })}
                </div>
                <div className="progress-bar-container">
                    <div className="progress-bar" style={{ width: `${progress || 0}%` }}></div>
                </div>

                <AnimatePresence>
                    {currentIndex === text.length && text.length > 0 && (
                        <motion.div 
                            className="overlay"
                            initial={{ opacity: 0, backdropFilter: "blur(0px)" }}
                            animate={{ opacity: 1, backdropFilter: "blur(8px)" }}
                        >
                            <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', textAlign: 'center', width: '100%' }}>
                                <h2 style={{ fontSize: '48px', marginBottom: '10px', color: '#fff' }}>Отличный результат!</h2>
                                <p style={{ fontSize: '20px', color: 'var(--text-main)', marginBottom: '30px' }}>
                                    Скорость: <strong style={{color: "#0ea5e9"}}>{stats.wpm} WPM</strong> | 
                                    Макс. комбо: <strong style={{color: "#f59e0b"}}>x{maxCombo}</strong>
                                </p>
                                <Button variant="primary" onClick={() => resetGame()} style={{ width: '250px', margin: '0 auto' }}>Новый раунд</Button>
                            </div>
                        </motion.div>
                    )}
                </AnimatePresence>
            </div>

            <div className="keyboard" style={{ display: 'flex', flexDirection: 'column', gap: '10px', alignItems: 'center', flexShrink: 0 }}>
                {currentLayout.map((row, rIndex) => (
                    <div key={`${lang}-${rIndex}`} className="key-row">
                        {row.map((key, kIndex) => {
                            const isSpace = key === " ";
                            const isTarget = key === expectedKey;
                            const isActive = key === pressedKey;
                            
                            let classNames = "key";
                            if (isSpace) classNames += " space";
                            if (isTarget) classNames += " target";
                            if (isActive) classNames += isErrorKey ? " error-active" : " active";

                            return (
                                <div key={`${lang}-${key}-${kIndex}`} className={classNames}>
                                    {isSpace ? "SPACE" : key}
                                </div>
                            );
                        })}
                    </div>
                ))}
            </div>
        </motion.div>
    );
}

Object.assign(window, { TypingTest });
